WIP
tolitius/envoy pull request #16
Opened 2024-12-07 22:35 UTC by arichiardi

Coming back from magnificent adventure I decided to take up the classic code-on-airplane project and port this project to babashka.

Alongside that, I was not able to have the `map->consul` function work locally (it seems there are a couple of bugs) so I am introducing a `map->consul2` function in replacement. This latter function takes advantage of `:offset` when querying the current consul map.

Here and there you can notice other fixes that I can try to segregate to different commits, if necessary.

2024-12-07 22:40 UTC, arichiardi commented on src/envoy/tools.cljc
> +  [v & [deserializer]]
this was a clj-kondo warning (docstring goes before params)

2024-12-07 22:41 UTC, arichiardi commented on src/envoy/core.cljc
> +         (tools/remove-empty-keys))))
Nota Bene

2024-12-09 22:11 UTC, tolitius requested changes

2024-12-09 22:11 UTC, tolitius commented on src/envoy/core.cljc
> +      (overwrite-with2 path m ops))))
this looks identical to the `map->consul`
besides the `overwrite-with2` call

see the `overwrite-with2` comment :)

2024-12-09 22:11 UTC, tolitius commented on src/envoy/core.cljc
> +              side-effect-ops))))
if this does what `overwrite-with` already does (+ the `offset`), than I don't think we need to create `overwrite-with2`, but rather keep it as `overwrite-with`, given that it does 100% of what the current `overwrite-with` does.

I understand `foo`, `foo2` talk by Rich, but names are too important to sacrifice
if we have a library with:

foo2
foo
bar3
bar
foo9
bar4

it would be quite difficult to select a proper "`foo`" and "`bar`" for the use case
even more difficult to make sense of the dependencies between foo13 and bar7

the reason is "`2`" or "`13`" convey little business context unless it is 2 miles per hour or $13.

2024-12-09 22:11 UTC, tolitius commented on src/envoy/session.cljc
> +       (throw (ex-info (str "could not GET from consul due to: " (error-message resp))
👍 
thanks for these

2024-12-09 22:15 UTC, arichiardi commented on src/envoy/core.cljc
> +              side-effect-ops))))
Yeah I do agree with you. 

The reason for that `2` is that I could not figured out a problem with the current version. I'll try again and see - I was getting a "path not found". I will get back to. you.

2024-12-09 22:40 UTC, arichiardi commented on src/envoy/core.cljc
> +              side-effect-ops))))
I think I found the bug - that `delete` in `overwrite-with` can never work because it does not carry the auth token - will push a small separate commit and move things around.

2024-12-09 22:48 UTC, arichiardi commented on src/envoy/core.cljc
> +              side-effect-ops))))
Going back to the naming thing probably a namespace2 makes more sense generally for achieving accretion

2024-12-10 15:40 UTC, arichiardi commented on src/envoy/core.clj
> -  [kv-path m & [{:keys [serializer overwrite?] :or {serializer :edn overwrite? false} :as ops}]]
This is just a renaming

2024-12-10 16:15 UTC, arichiardi commented on src/envoy/core.cljc
> +      (overwrite-with2 path m ops))))
Ok added a commit that fixes existing bugs and removes this function

2024-12-10 16:15 UTC, arichiardi commented on src/envoy/core.cljc
> +              side-effect-ops))))
Ok added a commit that fixes existing bugs and removes this function

2024-12-12 15:06 UTC, tolitius commented
thank you!

2024-12-12 15:06 UTC, merged

2024-12-12 15:09 UTC, tolitius commented
changes should be in:
```
{tolitius/envoy {:mvn/version "0.1.33-SNAPSHOT"}}
```